# Generated by Django 6.0.1 on 2026-01-31 14:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('data_hora_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('prazo', models.DateTimeField(blank=True, null=True)),
                ('concluida', models.BooleanField(default=False)),
                ('tags', models.ManyToManyField(related_name='tarefas', to='todoapp.tag')),
            ],
            options={
                'ordering': ['concluida', '-data_hora_criacao'],
            },
        ),
    ]
