# Generated by Django 6.0.1 on 2026-02-06 11:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='nome',
            new_name='name',
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('tags', models.ManyToManyField(related_name='tasks', to='todoapp.tag')),
            ],
            options={
                'ordering': ['is_completed', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Tarefa',
        ),
    ]
